### ISSUE TITLE
Req-Specs: Project Plan

### ISSUE THREAD

**Issue by cforonda** [PiWatcher/PiWatcher-Docs#59]
**ORIGINAL DUE DATE**: 11/4/2020 at 11:59pm

**Assigned to**: Champ

**Weight**: 5

**Useful resource**: [Assignment Specs](https://www.cefns.nau.edu/~edo/Classes/CS_Capstone/Assignments/Requirements.pdf)

**To Do**:
- [x] Create Gantt chart for the visualizing current schedule
- [x] Describe team's project plan for the rest of the semester
- [x] Explain how we plan to develop our product

**Acceptance Criteria**:
- [x] Above to-do is complete
- [x] Page(s) is uploaded on document
